name: Deploy to Cloud Run (hello)
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Auth (WIF)
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/397245976541/locations/global/workloadIdentityPools/github-pool/providers/github
          service_account: gha-deployer@quiet-branch-474004-v6.iam.gserviceaccount.com
      - name: Deploy
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          project_id: quiet-branch-474004-v6
          region: asia-northeast1
          service: formulatorpro-periodicexecution
          image: us-docker.pkg.dev/cloudrun/container/hello:latest
          allow_unauthenticated: true
      - name: Show URL
        run: echo "URL=${{ steps.deploy.outputs.url }}"