name: Deploy to Cloud Run Jobs

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: quiet-branch-474004-v6
  REGION: asia-northeast1
  SERVICE_ACCOUNT: gha-deployer-129@quiet-branch-474004-v6.iam.gserviceaccount.com
  REPOSITORY: cloud-run-source-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Auth (WIF)
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/397245976541/locations/global/workloadIdentityPools/github-pool/providers/github
          service_account: gha-deployer-129@quiet-branch-474004-v6.iam.gserviceaccount.com
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
      
      - name: Build and Push Docker image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/pdf-processor:${{ github.sha }} .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/pdf-processor:${{ github.sha }}
      
      - name: Deploy to Cloud Run Job
        run: |
          gcloud run jobs deploy pdf-processor-job \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/pdf-processor:${{ github.sha }} \
            --region=${{ env.REGION }} \
            --project=${{ env.PROJECT_ID }} \
            --service-account=${{ env.SERVICE_ACCOUNT }} \
            --max-retries=1 \
            --task-timeout=3600 \
            --no-cpu-throttling \
            --set-env-vars="GOOGLE_CLOUD_PROJECT=${{ env.PROJECT_ID }}" \
            --set-env-vars="ENVIRONMENT=production"